services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    build: ./fastapi_backend
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"

  frontend:
    build: ./nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
     build: ./nginx
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - /etc/ssl:/etc/nginx/ssl:ro
     restart: always
